services:
  postgres:
    container_name: clinic-manager-db
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=clinics
    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/init.sql

  # otel-collector:
  #   image: otel/opentelemetry-collector:0.108.0
  #   container_name: otel-collector
  #   command: [--config=/etc/otel-collector-config.yaml]
  #   volumes:
  #     - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
  #   ports:
  #     - 1888:1888 # pprof extension
  #     - 8888:8888 # Prometheus metrics exposed by the collector
  #     - 8889:8889 # Prometheus exporter metrics
  #     - 13133:13133 # health_check extension
  #     - 4317:4317 # OTLP gRPC receiver
  #     - 4318:4318 # OTLP HTTP receiver
  #     - 55679:55679 # zpages extension

  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - 16686:16686 # UI
      - 6831:6831/udp # Traces UDP
      - 14268:14268 # Traces HTTP
      - 4317:4317 # OTLP/gRPC
      - 4318:4318 # OTLP/HTTP
